services:
  database:
    container_name: database
    image: mongodb/mongodb-community-server:7.0-ubi9
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db
  minly-server:
    # to change container name, you have to rebuild the webapp image with then
    # new server host name
    container_name: minly-server
    image: davenchy/minly-assignment-server
    ports:
      - "3000:3000"
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: '3000'
      MONGO_HOST: 'database'
      MONGO_PORT: '27017'
    restart: on-failure
    depends_on:
      - database
    volumes:
      - uploads:/app/uploads
  minly-webapp:
    container_name: minly-webapp
    image: "davenchy/minly-assignment-webapp"
    ports:
      - '80:80'
    restart: on-failure
    depends_on:
      - minly-server

volumes:
  mongodb_data:
  uploads:
